<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Student extends \App\Entity\Student implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'quizmarks' => [parent::class, 'quizmarks', null],
        "\0".parent::class."\0".'quizzes' => [parent::class, 'quizzes', null],
        "\0".parent::class."\0".'ressources' => [parent::class, 'ressources', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'user_id' => [parent::class, 'user_id', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'id' => [parent::class, 'id', null],
        'quizmarks' => [parent::class, 'quizmarks', null],
        'quizzes' => [parent::class, 'quizzes', null],
        'ressources' => [parent::class, 'ressources', null],
        'user' => [parent::class, 'user', null],
        'user_id' => [parent::class, 'user_id', null],
        'username' => [parent::class, 'username', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
