<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ressources extends \App\Entity\Ressources implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'link' => [parent::class, 'link', null],
        "\0".parent::class."\0".'quizzes' => [parent::class, 'quizzes', null],
        "\0".parent::class."\0".'student' => [parent::class, 'student', null],
        "\0".parent::class."\0".'subject' => [parent::class, 'subject', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'id' => [parent::class, 'id', null],
        'link' => [parent::class, 'link', null],
        'quizzes' => [parent::class, 'quizzes', null],
        'student' => [parent::class, 'student', null],
        'subject' => [parent::class, 'subject', null],
        'type' => [parent::class, 'type', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
