<?php

namespace ContainerIvTH52H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangeRoleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ChangeRoleController' shared autowired service.
     *
     * @return \App\Controller\ChangeRoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ChangeRoleController.php';

        $container->services['App\\Controller\\ChangeRoleController'] = $instance = new \App\Controller\ChangeRoleController(($container->services['router'] ?? self::getRouterService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ChangeRoleController', $container));

        return $instance;
    }
}
