<?php

namespace ContainerIvTH52H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntitySubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\EntitySubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\EntitySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/EventSubscriber/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/EntitySubscriber.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\EventSubscriber\\EntitySubscriber'])) {
            return $container->privates['App\\EventSubscriber\\EntitySubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\EntitySubscriber'] = new \App\EventSubscriber\EntitySubscriber($a, ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
