<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHKe1Jmv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHKe1Jmv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHKe1Jmv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHKe1Jmv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHKe1Jmv\App_KernelDevDebugContainer([
    'container.build_hash' => 'HKe1Jmv',
    'container.build_id' => '5be72381',
    'container.build_time' => 1687335930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHKe1Jmv');
