<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZrGPSZs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZrGPSZs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZrGPSZs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZrGPSZs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZrGPSZs\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZrGPSZs',
    'container.build_id' => '77a19fa2',
    'container.build_time' => 1687251094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZrGPSZs');
