<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIvTH52H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIvTH52H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIvTH52H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIvTH52H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIvTH52H\App_KernelDevDebugContainer([
    'container.build_hash' => 'IvTH52H',
    'container.build_id' => '027fd506',
    'container.build_time' => 1687293611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIvTH52H');
