<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_fortawesome_fontawesome-free_js_brands_js-node_modules_fortawesome_fonta-0173da.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'langues' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/langues.js',
            ],
        ],
        'roles' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/roles.js',
            ],
        ],
        'anim' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_fill_js-node_modules_core-js_modules_es_array_p-7bcc47.js',
                '/build/anim.js',
            ],
        ],
    ],
],

]];
